2015 day2 java
Eltryo/advent-of-code-java pull request #3
Opened 2021-10-02 13:01 UTC by Eltryo

2021-10-02 14:22 UTC, DanielMerkl requested changes
Über alle Files nochmal `STRG + ALT + L`, es fehlt öfter mal ein Zeilenumbruch am Ende der Datei.

Bei Fragen kannst du mich jederzeit auf Discord anstupsen 😄  (können gerne auch einen Call machen falls die Kommentare nicht klar genug sind)

2021-10-02 14:22 UTC, DanielMerkl commented on src/test/java/year2015/day2/PresentTest.java
> +class PresentTest {
sehr gut 👍  mir fällt nichts ein, was man besser machen könnte

2021-10-02 14:22 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    }
Der Gedanke geht auf jeden Fall in die richtige Richtung (Vermeidung von doppeltem Code).

Die Logik, wie aus einem String ein Present entsteht sollte aber nicht das Anliegen von dem PresentsCalculator sein, sondern von der Klasse Present. (Man könnte beispielsweise im Present eine statische Methode `fromInput(String input) {...}` machen, welche ein fertiges Present zurückgibt 😉

2021-10-02 14:22 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public final String[] lines;
Das hier sollte bereits die "fertige" Datenstruktur sein, mit welcher die Klasse arbeiten kann. Man würde sich innerhalb der Klasse leichter tun, wenn das bereits ein fertiges `Present[]` wäre. 

(Haben wir zwar noch nicht besprochen, aber noch besser wäre `List<Present>`. Diese Datenstruktur kannst du dir gerne schon mal anschauen 😄 )

2021-10-02 14:22 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public int sumOfRibbonLength = 0;
Diese beiden Helfer-Variablen könnten vom Scope her noch besser versteckt sein. "Global" innerhalb der Klasse wäre auch richtig, aber ich persönlich würde die innerhalb der Funktionen erst deklarieren (ist vermutlich eher Geschmacksache)

2021-10-02 17:47 UTC, Eltryo commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public final String[] lines;
Hab eine Lösung gefunden, aber bin mir nicht sicher, ob du das meintest. Zumindest funktioniert es. 😅

2021-10-03 06:49 UTC, DanielMerkl requested changes

2021-10-03 06:49 UTC, DanielMerkl commented on src/main/java/year2015/day2/Present.java
> +    }
Fast richtig 😁  die Abbildung geht gerade von `String -> ArrayList<Present>`, sollte aber meiner Meinung nach von `String -> Present` gehen, da sich die Present-Klasse nicht um alle Presents kümmern soll (dafür ist ja die Klasse PresentsCalculator)

2021-10-03 06:50 UTC, DanielMerkl requested changes

2021-10-03 06:50 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public final ArrayList<Present> lines;
Variablenname `lines` geht noch präziser 😉

2021-10-03 06:54 UTC, DanielMerkl commented on src/test/java/year2015/day2/PresentTest.java
> +class PresentTest {
Mir ist gerade aufgefallen, dass `PresentTest` gerade die Logik von `PresentCalculator` testet 😄 
Für jede Klasse bräuchten wir jeweils einen Test. `PresentTest` sollte sich nur mit der Funktionsweise **eines** Presents beschäftigen und `PresentCalculatorTest` um die Logik für **mehrere** Presents

2021-10-03 09:46 UTC, Eltryo commented
Hab so ein bisschen herumexperimentiert und hab ne Lösung gefunden, bin mir aber nicht sicher ob du das darauf hinaus wolltest. 😅

2021-10-03 11:34 UTC, DanielMerkl requested changes

2021-10-03 11:34 UTC, DanielMerkl commented on src/main/java/year2015/day2/Present.java
> +    }
👌

2021-10-03 11:34 UTC, DanielMerkl commented on src/main/java/year2015/day2/Present.java
> +    }
Die beiden Methoden sind nur innerhalb der Klasse von Relevanz und sollten nicht von außen aufrufbar sein

2021-10-03 11:34 UTC, DanielMerkl commented on src/main/java/year2015/day2/Present.java
> +    }
gleiches gilt für `bow()` und `ribbon()`

2021-10-03 11:34 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public ArrayList<Present> presents = new ArrayList<>();
die Variable sollte `final` sein, da sie sich nach der Konfiguration/Instanziierung des Moduls nicht mehr verändern dürfte (nach Möglichkeit sollte man Immutability generell bevorzugen. Aus ähnlichen Gründen bevorzugt man in JS `const` vor `let` wo es möglich ist)

2021-10-03 11:34 UTC, DanielMerkl commented on src/main/java/year2015/day2/PresentsCalculator.java
> +    public ArrayList<Present> presents = new ArrayList<>();
diese Änderung hätte zu Folge, dass `handleInput(...)` geinlined werden müsste, was meiner Meinung nach in Ordnung ist

2021-10-03 11:34 UTC, DanielMerkl commented on src/test/java/year2015/day2/PresentCalculatorTest.java
> +class PresentCalculatorTest {
hier kannst du gerne noch Tests ergänzen, wo nicht der echte Input reingeschossen wird. Part 1 könnte beispielsweise mit dem String `2x3x4\n1x1x10` aufgerufen werden und der erwartete Wert wäre entsprechend 101 (58 + 43)

2021-10-03 11:34 UTC, DanielMerkl commented on src/test/java/year2015/day2/PresentCalculatorTest.java
> +class PresentCalculatorTest {
In dem Fall könnte man schon von einem sogenannten "Integrations-Test" sprechen, da sowohl das Modul `CalculatePresents` als auch indirekt das Modul "Present" getestet wird

2021-10-03 16:55 UTC, DanielMerkl approved these changes

2021-10-03 16:55 UTC, merged